# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Standard libraries

import os
import math
import numpy as np
import time

## Imports for plotting
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

#matplotlib_inline.backend_inline.set_matplotlib_formats()
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

In [ ]:
# Import torch
import torch

# Create random tensor
a = torch.rand(7,7)
print(a)

tensor([[0.2179, 0.9392, 0.4268, 0.8698, 0.7493, 0.5530, 0.2509],
        [0.1044, 0.4878, 0.7734, 0.3751, 0.7587, 0.5447, 0.3047],
        [0.4412, 0.0771, 0.4410, 0.0375, 0.5115, 0.9961, 0.0414],
        [0.5836, 0.9922, 0.6683, 0.4271, 0.4883, 0.1530, 0.7450],
        [0.5406, 0.4631, 0.7400, 0.1905, 0.5403, 0.8493, 0.0628],
        [0.9622, 0.8588, 0.4323, 0.5559, 0.5182, 0.5360, 0.2544],
        [0.9453, 0.3968, 0.9904, 0.0822, 0.1483, 0.2112, 0.7576]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
b = torch.rand(1,7)
print(b)

# Taking transpose of 2nd tensor to perform matrix multiplication
bT = torch.transpose(b, 0, 1)
print(bT)

# Perform matrix multiplication
c = torch.matmul(a, bT)
print(c)

tensor([[0.9475, 0.7928, 0.8248, 0.3862, 0.1294, 0.8179, 0.3812]])
tensor([[0.9475],
        [0.7928],
        [0.8248],
        [0.3862],
        [0.1294],
        [0.8179],
        [0.3812]])
tensor([[2.2839],
        [1.9282],
        [1.7540],
        [2.5280],
        [2.3518],
        [2.7662],
        [2.5395]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
d = torch.manual_seed(0)
print(d)

# Create two random tensors
e = torch.randn(2,3)
f = torch.randn(3,5)

# Matrix multiply tensors
ef = torch.matmul(e,f)
print(ef)

tensor([[ 1.8020,  0.7298,  0.5121,  2.9808, -1.7624],
        [ 0.8239,  0.8836, -0.3549,  3.0431, -0.9902]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed

# Set CPU random seed
torch.manual_seed(1234)

# Check for access to GPU
# finding and setting the right computational device
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(device)

# Create two random tensors on GPU
a = torch.rand(3,5).to(device)
b = torch.rand(5,4).to(device)
print(a)
print(b)

cuda
tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583],
        [0.7006, 0.0518, 0.4681, 0.6738, 0.3315],
        [0.7837, 0.5631, 0.7749, 0.8208, 0.2793]], device='cuda:0')
tensor([[0.6817, 0.2837, 0.6567, 0.2388],
        [0.7313, 0.6012, 0.3043, 0.2548],
        [0.6294, 0.9665, 0.7399, 0.4517],
        [0.4757, 0.7842, 0.1525, 0.6662],
        [0.3343, 0.7893, 0.3216, 0.5247]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
ab = torch.matmul(a,b)
print(ab)

tensor([[0.6711, 0.8345, 0.4083, 0.5015],
        [1.2415, 1.4724, 1.0317, 1.0148],
        [1.9175, 2.1738, 1.4744, 1.3740]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
maxV = max(ab.flatten())
print(maxV)

maxVal = torch.max(ab)
print(maxVal)

# Find min
minVal = torch.min(ab)
print(minVal)

tensor(2.1738, device='cuda:0')
tensor(2.1738, device='cuda:0')
tensor(0.4083, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_in = torch.argmax(ab)
print(max_in)

# Find arg min
min_in = torch.argmin(ab)
print(min_in)

tensor(9, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a = torch.rand(1,1,1,10)

# Remove single dimensions
b = torch.squeeze(a)

# Print out tensors and their shapes
print(a)
a.size()

print(b)
b.size()


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


torch.Size([10])